'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_Notensatz
    Public Property id_NotensatzNr As Integer
    Public Property dt_Titel As String
    Public Property dt_Untertitel As String
    Public Property dt_Interpret As String
    Public Property dt_Arrangeur As String
    Public Property dt_Verlag As String

    Public Overridable Property tbl_Stimme As ICollection(Of tbl_Stimme) = New HashSet(Of tbl_Stimme)

End Class
