'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_Stimme
    Public Property id_StimmeNr As Integer
    Public Property dt_StimmeName As String

    Public Overridable Property tbl_Notensatz As ICollection(Of tbl_Notensatz) = New HashSet(Of tbl_Notensatz)

End Class
