'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_Notensatz
    Public Property id_NotensatzNr As Integer
    Public Property dt_Titel As String
    Public Property dt_Untertitel As String
    Public Property dt_Interpret As String
    Public Property dt_Arrangeur As String
    Public Property dt_Verlag As String

    Public Overridable Property tbl_Stimme As ICollection(Of tbl_Stimme) = New HashSet(Of tbl_Stimme)

End Class
